name: demo

on: 
  - push 
  - workflow_dispatch

jobs:
  demo1: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      - name: Execution
        run: bash demo.sh

      - name: First action
        uses: ./.github/actions/first-action

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: report
          path: reports/report.txt