name: org

on: 
  - push

jobs:
  e2e-test: 
    runs-on: ubuntu-latest

    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github.event.head_commit.message) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: madedotcom/alliance
          token: ${{ secrets.MADE_PAT }}

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          #conclusion: failed
      

    