name: org

on: 
  - workflow_dispatch

jobs:
  e2e-test: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: madedotcom/alliance
          token: ${{ secrets.MADE_PAT }}

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
      

    