name: IO

on: 
  - workflow_dispatch

jobs:
  build:
    timeout-minutes: 10 
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      
      - run: echo "::echo::off"
      
      - name: get-token
        run: ./token.sh
        id: get-token
      
      - name: use token
        run: |
          echo "::group::TOKEN GROUP"
          echo ${{ steps.get-token.outputs.BUILD_TOKEN}} 
          echo "@@@@@@@@@@@@@@@@@@@@@@@@@@"
          echo "::end-group::"
          echo "Out of TOKEN GROUP"


       