name: IO

on: 
  - workflow_dispatch

jobs:
  build: 
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      
      - run: echo "::echo::on"
      
      - name: get token
        run: ./token.sh
        id: token
      
      - name: use token
        run: |
          echo ${{ steps.token.outputs.BUILD_TOKEN}} 

  # test: 
  #   runs-on: ubuntu-latest
  #   id: test1

  #   steps:
  #     - name: test
  #       run: |
  #         echo ${{ jobs.test1.output.BUILD_TOKEN}} 
       