name: IO

on: 
  - workflow_dispatch
  - repository_dispatch

jobs:
  build:
    timeout-minutes: 10 
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - run: echo "github = ${{ toJSON(github) }}"
      
      - run: echo "::echo::on"
      
      - name: get-token
        run: |
          ./token.sh
          echo "TEST=FIRST TEST" >> $GITHUB_ENV
        id: get-token
      
      - name: use token
        run: |
          echo "::group::TOKEN GROUP"
          echo ${{ steps.get-token.outputs.BUILD_TOKEN}} 
          echo "@@@@@@@@@@@@@@@@@@@@@@@@@@"
          echo "::endgroup::"
          echo "Out of TOKEN GROUP: $TEST"
          # cat --f

      - name: run always
        id: input-job
        if: ${{ always() }}
        run: echo "ALWAYS ${{ input-job.inputs.name }}" 
        with:
          name: qatools
        


       